name: Build and Push Docker Image to Docker Hub and GHCR

on:
  push:
    tags:
      - '*'  # Trigger on any new tag

jobs:
  push_to_registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract version and lowercase repo owner
        id: prep
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REPO_OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            debjyoti89/experiment-docker:latest
            debjyoti89/experiment-docker:${{ env.VERSION }}
            ghcr.io/debjyotic/experiment-docker:latest
            ghcr.io/debjyotic/experiment-docker:${{ env.VERSION }}
